### ISSUE TITLE
CUDA conflict of MobileStereoNet3d

### ISSUE THREAD

**Issue by lwwdww** [Jieqianyu/SGN#11]
Hello, thanks for sharing this wonderful work.

The CUDA version for the project (11.1) and for the MobileStereoNet3d (10.0) seems to be conflicting. Could you provide a download link for the generated depth and pseudo point cloud?

**Comment by Jieqianyu** [comment]
Thank you for your feedback on the project. You can use conda to install different versions of cuda toolkit for these environments.

**Comment by Jieqianyu** [comment]
Since the generated depth and pseudo point cloud files are too large to upload, you might consider generating them by yourself, which will be faster.
