### ISSUE TITLE
There are resources available for visualizing code？

### ISSUE THREAD

**Issue by Samsara011** [Jieqianyu/SGN#13]
Hello author, thank you for your excellent work. I was wondering if you could share the visualization code for the project? Looking forward to your reply！

**Comment by Jieqianyu** [comment]
Thank you for your interest in our work. You can save the predictions by setting the `save_flag` in model configs and then visualize the results using the tools in [semantic-kitti-api](https://github.com/PRBonn/semantic-kitti-api).

**Comment by Samsara011** [comment]
Ok, I see. Thank you for your reply
