### ISSUE TITLE
About FOV mask shape in paper.

### ISSUE THREAD

**Issue by hongxiaoy** [Jieqianyu/SGN#2]
<img width="610" alt="image" src="https://github.com/Jieqianyu/SGN/assets/112234465/fcc2ac30-7757-437e-a69d-a112bb48a423">
Hi, thanks for your nice work. I have a question when I read the paper, just as the image shown, in my opinion this mask should be a 3D mask for voxels, with voxels projected outside the image be False, and projected in the image be True. I don't know if my understanding has some bias.
Hope your reply, thanks~

**Comment by Jieqianyu** [comment]
Thank you for your interest in our work. You are right, it is indeed a 3D mask for voxels. We are sorry that this typo error confused you. Thank you again for reading carefully and helping us correct our mistakes!
