### ISSUE TITLE
I did not find image_2 and image_3 in the official SemanticKITTI dataset

### ISSUE THREAD

**Issue by lcl124252** [Jieqianyu/SGN#4]
I did not find image_2 and image_3 in the official SemanticKITTI dataset. Where should I find these two folders?

**Comment by Jieqianyu** [comment]
Thanks for your interest! You need to download the color images from kitti odometry (https://s3.eu-central-1.amazonaws.com/avg-kitti/data_odometry_color.zip).

**Comment by lcl124252** [comment]
> Thanks for your interest! You need to download the color images from kitti odometry (https://s3.eu-central-1.amazonaws.com/avg-kitti/data_odometry_color.zip).

Thank you very much for your reply！
