### ISSUE TITLE
模型是否能像MonoScene一样直接从图像端到端预测？

### ISSUE THREAD

**Issue by 123456bfb** [Jieqianyu/SGN#6]
你好，我发现你们论文里提到这是一个端到端的模型，但我在推理的时候仍然需要输入预处理的伪点云.bin数据，请问模型是否能像MonoScene一样直接从图像端到端预测？

**Comment by Jieqianyu** [comment]
为了训练方便，我们事先用深度预测结果处理好伪点云，在测试的时候，深度预测是可以并入到整个pipeline的
