### ISSUE TITLE
请问我训练完成后如何使用测试集进行测试

### ISSUE THREAD

**Issue by lcl124252** [Jieqianyu/SGN#7]
感谢你们的优秀工作，我将配置里面的val改成test发现运行结果是0，我想请问一下如果想进行测试应该怎么做![MOP 0`NUTFX6TM`V{DP%A7W](https://github.com/Jieqianyu/SGN/assets/70134213/7e761d58-9876-497d-b114-546c247f119f)

**Comment by lcl124252** [comment]
![53W5D$XD}SU$Q~75RCL_31I](https://github.com/Jieqianyu/SGN/assets/70134213/c91b99f3-67c4-4692-a0d6-90788241a3dc)

**Comment by Jieqianyu** [comment]
感谢对我们工作的关注！semantickitti上的测试集没有提供anno，是在网站上进行评测的，需要把ssc 结果保存下来，上传到网站进行评测。

**Comment by lcl124252** [comment]
> 感谢对我们工作的关注！semantickitti上的测试集没有提供anno，是在网站上进行评测的，需要把ssc 结果保存下来，上传到网站进行评测。

感谢你的回答，请问你们有保存ssc结果的脚本吗？如果有的话可以发给我一下吗？我的邮箱是1242520599@qq.com，非常感谢

**Comment by lcl124252** [comment]
> 感谢对我们工作的关注！semantickitti上的测试集没有提供anno，是在网站上进行评测的，需要把ssc 结果保存下来，上传到网站进行评测。

非常抱歉，我已经找到保存的设置了，是我之前没有仔细看代码，给你们造成不必要的问题
